name: Update README with greeting

on:
  schedule:
    - cron: '0 6,12,18,23 * * *'  # Executa às 06:00, 12:00, 18:00 e 23:00 todos os dias
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Generate greeting
      id: generate_greeting
      run: |
        # Execute o script JavaScript para obter a saudação
        GREETING=$(node greeting.js)
        echo "GREETING=$GREETING" >> $GITHUB_ENV

    - name: Update README with new greeting
      run: |
        # Substitua a saudação antiga pela nova no README.md
        sed -i -E "s/(<!-- GREETING -->\n)[^\n]*(\n)/\1${{ env.GREETING }}\2/" README.md || echo -e "\n<!-- GREETING -->\n${{ env.GREETING }}" >> README.md

    - name: Commit changes
      run: |
        git config --local user.email "rodrigo.vilemen@hotmail.com"
        git config --local user.name "r-vilemen"
        git add README.md
        git commit -m "update: replace greeting"
        git push
