name: Update README with greeting

on:
  schedule:
    - cron: '0 6,12,18,23 * * *' # Executa às 06:00, 12:00, 18:00 e 23:00 todos os dias
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get current hour in Brasília timezone
      run: echo "::set-output name=hour::$(TZ='America/Sao_Paulo' date +%H)"
      id: time

    - name: Generate greeting based on time
      run: |
        HOUR=${{ steps.time.outputs.hour }}

        if [ $HOUR -ge 6 ] && [ $HOUR -lt 12 ]; then
          GREETING="Bom dia"
        elif [ $HOUR -ge 12 ] && [ $HOUR -lt 18 ]; then
          GREETING="Boa tarde"
        elif [ $HOUR -ge 18 ] && [ $HOUR -lt 24 ]; then
          GREETING="Boa noite"
        else
          GREETING="Boa madrugada"
        fi

        echo "::set-output name=greeting::$GREETING"
      id: greeting

    - name: Update README
      run: |
        GREETING=${{ steps.greeting.outputs.greeting }}
        sed -i "s|{{GREETING}}|$GREETING|" README.md

    - name: Commit changes
      run: |
        git config --local user.email "rodrigo.vilemen@hotmail.com"
        git config --local user.name "r-vilemen"
        git add README.md
        git commit -m "update: greeting"
        git push
