name: Update README with greeting

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get current hour
      id: time
      run: echo "hour=$(date +%H)" >> $GITHUB_ENV

    - name: Generate greeting based on time
      id: greeting
      run: |
        HOUR=${{ env.hour }}

        if [ $HOUR -ge 6 ] && [ $HOUR -lt 12 ]; then
          echo "GREETING=Bom dia, visitante!" >> $GITHUB_ENV
        elif [ $HOUR -ge 12 ] && [ $HOUR -lt 18 ]; then
          echo "GREETING=Boa tarde, visitante!" >> $GITHUB_ENV
        elif [ $HOUR -ge 18 ] && [ $HOUR -lt 24 ]; then
          echo "GREETING=Boa noite, visitante!" >> $GITHUB_ENV
        else
          echo "GREETING=Boa madrugada, visitante!" >> $GITHUB_ENV
        fi

    - name: Update README.md
      run: |
        sed -i "s|<!-- GREETING -->|${{ env.GREETING }}|" README.md

    - name: Commit changes
      run: |
        git config --local user.email "rodrigo.vilemen@hotmail.com"
        git config --local user.name "Rodrigo Vilemen"
        git add README.md
        git commit -m "update: readme.md" || echo "No changes to commit"
        git push
