name: Update README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run greeting script
        run: |
          node generateGreeting.js > greeting.txt

      - name: Update README
        run: |
          sed -i '/<!-- start-greeting -->/,/<!-- end-greeting -->/{/<!-- start-greeting -->/{p; r greeting.txt
            }; /<!-- end-greeting -->/p; d}' README.md

      - name: Commit changes
        run: |
          git config --local user.email "rodrigo.vilemen@hotmail.com"
          git config --local user.name "r-vilemen"
          git add README.md
          git commit -m "update: greeting"
          git push
