name: Update Projects

on:
  schedule:
    - cron: "0 3 * * *" # Atualiza às 24h do horário de Brasília.
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependencies
        run: yarn

      - name: Run pinned projects script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node scripts/updateProjects.mjs

      - name: Check for changes and commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --local user.email "rodrigo.vilemen@hotmail.com"
            git config --local user.name "r-vilemen"
            git add README.md
            git commit -m "update: pinned projects"
            git push
          fi
