name: Update README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run greeting script
        run: |
          node generateGreeting.js > greeting.txt

      - name: Update README
        run: |
          # Substitui o conteúdo entre os marcadores de saudação
          sed -i.bak '/<!-- start-greeting -->/,/<!-- end-greeting -->/ {
            /<!-- start-greeting -->/! {
              /<!-- end-greeting -->/!d
            }
            /<!-- start-greeting -->/ {
              r greeting.txt
              d
            }
          }' README.md
          # Remove o backup
          rm README.md.bak

      - name: Commit changes
        run: |
          git config --local user.email "rodrigo.vilemen@hotmail.com"
          git config --local user.name "r-vilemen"
          git add README.md
          git commit -m "update: greeting"
          git push
