name: Update Greeting

on:
  schedule:
    - cron: "53 8,14,20,2 * * *" # Atualiza às 6h, 12h, 18h, e 24h do horário de Brasília.
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Log Current Time
        run: date -u

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run greeting script
        run: |
          node scripts/generateGreeting.js

      - name: Check for changes and commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
          git config --local user.email "rodrigo.vilemen@hotmail.com"
          git config --local user.name "r-vilemen"
          git add README.md
          git commit -m "update: greeting"
          git push
          echo "Changes committed"
          fi
