name: Update README with greeting

on:
  schedule:
    - cron: '0 6,12,18,23 * * *'  # Executa às 06:00, 12:00, 18:00 e 23:00 todos os dias
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Get current hour in Brasília timezone
      run: echo "HOUR=$(TZ='America/Sao_Paulo' date +%H)" >> $GITHUB_ENV

    - name: Generate greeting based on time
      id: generate_greeting
      run: |
        if [ "$HOUR" -ge 6 ] && [ "$HOUR" -lt 12 ]; then
          GREETING="Bom dia"
        elif [ "$HOUR" -ge 12 ] && [ "$HOUR" -lt 18 ]; then
          GREETING="Boa tarde"
        elif [ "$HOUR" -ge 18 ] && [ "$HOUR" -lt 24 ]; then
          GREETING="Boa noite"
        else
          GREETING="Boa madrugada"
        fi

        echo "GREETING=$GREETING" >> $GITHUB_ENV

    - name: Update README
      run: |
        # Remove the old greeting and add the new one
        sed -i -E "s/(<!-- GREETING -->\n)[^\n]*(\n)/\1$GREETING\2/" README.md || echo -e "\n<!-- GREETING -->\n$GREETING" >> README.md

    - name: Commit changes
      run: |
        git config --local user.email "rodrigo.vilemen@hotmail.com"
        git config --local user.name "r-vilemen"
        git add README.md
        git commit -m "update: replace greeting"
        git push
